### PR TITLE
[WIP] SVGEmbeddedFont & SVGEmbeddedImage

### PR DESCRIPTION
**Pull request by MatthiasKuehneEllerhold**
Add classes for embedding fonts and images into the SVG to get self-contained SVGs.

What I couldnt figure out is: What do I have to do in order to make Rasterization work? My local tests (even without embedding anything) weren't successfully.

### CODE REVIEW

**Comment by MatthiasKuehneEllerhold** [comment]
I've merged both of my Embedded classes into the already existing classes. Rasterization should now work with both. 

Additionaly I've added SVGClipPath - but how do we rasterize this? I've found this way for Imagick, dont know how to translate this to GD:
```
$imagick = new \Imagick($imagePath);
$imagick->setImageMatte(true);
$mask = new \Imagick($maskPath);

// Resize if necessary
$mask->resizeImage(
  $imagick->getImageWidth(),
   $imagick->getImageHeight(),
   \Imagick::FILTER_LANCZOS2SHARP,
   0.7
);

// Apply the alpha channel of $mask to $imagick:
// This will make every pixel in $imagick transparent that is transparent in $mask
$imagick->compositeImage($mask, \Imagick::COMPOSITE_DSTIN, 0, 0);
```

**Comment by meyfa** [comment]
Thanks a lot for your contribution! I'm happy to merge it.

> Additionaly I've added SVGClipPath - but how do we rasterize this? I've found this way for Imagick, dont know how to translate this to GD

To be honest, I don't know either. It seems that there is a way by creating a temporary mask image with a specific color outside the clip polygon, then merging that mask with the original image, and finally setting the chosen outside color to be transparent (see e.g. [ImageArtist](https://github.com/Treinetic/ImageArtist/blob/483b966dca51eb809aeb048df460e26311c23db1/src/lib/Shapes/PolygonShape.php#L86)). The downside is that if the image contains any pixels with that chosen color, they will become transparent, too. I'll try to find out if there's a way to do this efficiently.

**Comment by MatthiasKuehneEllerhold** [comment]
@meyfa Could you release a new version with this changes please?

**Comment by MatthiasKuehneEllerhold** [comment]
@meyfa Could you release a new version with this changes please (please!)?

**Pull request merged**
