### PR TITLE
Add Path Data object representation, parsing and management

### PR DESCRIPTION
**Pull request by lumnn**
This PR adds a class `SVGPathData`

This class is an object representation of `<path>`-s `d` attribute.

You can either create new instance and add commands with `addCommand` method to add objects representing single path command, or use `fromString` static method that will parse path string and create objects from it.

The class is built as a linked list, where it keeps only track of latest added command. When adding new command it's also is given it's previous command, as that sometimes needed.

The idea came up from this project - https://github.com/benjamminf/warpjs#api and the fact I need transform functionality like that on my personal project, so I thought I'll contribute. 

It's still requires a bit of work, but majority is finished. I'm adding a PR to gather your thoughts on this before I finish the rest.

### CODE REVIEW

**Comment by lumnn** [comment]
`transform` method is actually wrong, and does not behave 100% same as in referenced libary - will look into that

**Comment by lumnn** [comment]
- Added remaining command classes
- Added almost 100% test coverage
- Simplified the transform method that leaves more control to the passed transformer command

I'm considering this ready to merge. I haven't heard from you so far on this one. If you're not willing to merge this code, then no worries - just let me know and I'll sort myself. Like I said I preferred to contribute rather than create another package for the functionality closely related to SVG and this rpeository

**Comment by meyfa** [comment]
Thanks for contributing! I appreciate it, although I'm not sure I understood how this is intended to be used. Could you elaborate a bit on the intended use case & why that cannot be achieved with the current functionality? There is a lot of overlap here with the existing path parser implementation, but of course, that one isn't object-oriented.

**Comment by lumnn** [comment]
Basically the path instructions in SVGPath are just a string, which is harder to manipulate.
With this object representation you can either build/parse the path d argument and benefit from object oriented structure (for example keep references to parts of the path and then manipulate them).

How we use it in private project is that we build it from scratch.

```php
$path = new SVGPath();

$data = new SVGPathData();

$data->addCommand(new Move(0, 0));

$topLine = new Line(20, 0);
$data->addCommand($topLine);

$rightLine = new Line(20, 20);
$data->addCommand($rightLine);

// at this point I have a references to $topLine and $rightLine, which I can use to modify individually, for example I can move them by 20px

$topLine->x += 20;
$rightLine->x += 20;

// convert the instructions to string and save as d param
$path->setArgument('d', $data->__toString());
```

By using a parser you can instantiate all objects representing specific parts of a path and for example modify them.

```php
$path = $this->getPathFromSVG();

$pathData = SVGPathData::fromString($path->getArgument('d'));

// loop for each command in reverse order and possibly change/read parts of the path
foreach ($pathData as $command) {
  if ($command instanceof Line) {
    // move each line coordinates by 20px
    $command->x += 20;
  }
}

// alternatively you can use `transform` method that runs against each command and allows replacing them. In this example I replace all bezier curves with straight lines
$pathData->transform(function (PathDataCommandInterface $command) {
  if ($command instanceof BezierCurve) {
    return new Line($command->x, $command->y);
  }
});

// update the path
$path->setArgument('d', $pathData->__toString());
```

On above example the loop goes in reverse order, but that can be easily used on correct order with `array_reverse(iterator_to_array($pathData))`.

PathData class or transform method does have a potential for more scenarios (like injecting commands), but that wasn't needed in my scenarios so I didn't develop that.


Possibly the changes could be integrated better with `SVGPath` class, but I didn't go for that option as I didn't see much benefits over instantiating it on demand with `new` keyword and updating path `d` argument with `setAttribute('d', $data->__toString());`

The above examples are rather simple and more like for illustration purposes, but with more instructions in plain string it becomes more useful and readable with object approach

**Comment by meyfa** [comment]
I see, thanks for the explanation! I think this would make more sense as a separate library. It's such a large API surface that I'm hesitant to merge at this point. Regarding integration with SVGPath parsing:

* If we did use it for SVGPath parsing, we'd likely reduce performance significantly, due to extreme amounts of class instantiation.
* If we don't use it, then it's completely separate anyway, so it could also be its own library.

If you choose to publish this, I can offer adding a piece in the README so people can find it - would that be of interest to you?

Also, thanks again for your interest in PHP-SVG, even if this particular feature didn't get merged.

**Pull request closed without merging**
