### PR TITLE
feat: Add LIBXML_PARSEHUGE flag to allow larger content

### PR DESCRIPTION
**Pull request by walidaalhomsi**

### CODE REVIEW

**Comment by meyfa** [comment]
Closes #132

**Comment by meyfa** [comment]
Thanks for the PR! Is the `LIBXML_NSCLEAN` absolutely required? I'd prefer not to modify the document unless requested by the library user.

**Comment by walidaalhomsi** [comment]
I do not think it is, I have removed it.

**Review by meyfa — APPROVED** [review]
Looks good to me, thanks!

**Pull request merged**
